"""Name check against a verified list, and frequency codes in plain words. No network."""
import difflib
import re

DISCLAIMER = ("This report is generated by an AI assistant for a hackathon. Always consult a human doctor "
              "or pharmacist before making any medical decisions.")

# ponytail: small hand-made list of common Indian brands; swap for a real drug database (CSV) when one exists
VERIFIED = {
    "Dolo 650": "Paracetamol 650 mg", "Crocin": "Paracetamol", "Calpol": "Paracetamol", "Pan 40": "Pantoprazole 40 mg",
    "Pan D": "Pantoprazole + Domperidone", "Pantop 40": "Pantoprazole 40 mg", "Omez": "Omeprazole",
    "Rantac": "Ranitidine", "Razo 20": "Rabeprazole 20 mg", "Azithral 500": "Azithromycin 500 mg",
    "Augmentin 625": "Amoxicillin + Clavulanic acid", "Mox 500": "Amoxicillin 500 mg", "Taxim-O": "Cefixime",
    "Cifran 500": "Ciprofloxacin 500 mg", "Cetzine": "Cetirizine 10 mg", "Allegra 120": "Fexofenadine 120 mg",
    "Montair LC": "Montelukast + Levocetirizine", "Levocet": "Levocetirizine", "Folvite": "Folic acid 5 mg",
    "Shelcal 500": "Calcium carbonate + Vitamin D3", "Becosules": "Vitamin B complex + Vitamin C",
    "Neurobion Forte": "Vitamin B1, B6, B12", "Limcee": "Vitamin C", "Thyronorm": "Levothyroxine",
    "Eltroxin": "Levothyroxine", "Ecosprin 75": "Aspirin 75 mg", "Clopilet 75": "Clopidogrel 75 mg",
    "Glycomet 500": "Metformin 500 mg", "Glycomet GP 1": "Metformin + Glimepiride", "Janumet": "Sitagliptin + Metformin",
    "Amaryl 1": "Glimepiride 1 mg", "Telma 40": "Telmisartan 40 mg", "Amlong 5": "Amlodipine 5 mg",
    "Atorva 10": "Atorvastatin 10 mg", "Rosuvas 10": "Rosuvastatin 10 mg", "Zerodol-P": "Aceclofenac + Paracetamol",
    "Combiflam": "Ibuprofen + Paracetamol", "Brufen 400": "Ibuprofen 400 mg", "Meftal Spas": "Mefenamic acid + Dicyclomine",
    "Ondem 4": "Ondansetron 4 mg", "Domstal": "Domperidone", "Cyclopam": "Dicyclomine + Paracetamol",
    "Sinarest": "Paracetamol + Phenylephrine + Chlorpheniramine", "Ascoril LS": "Ambroxol + Levosalbutamol + Guaifenesin",
    "Asthalin": "Salbutamol", "Deriphyllin": "Etofylline + Theophylline", "Metrogyl 400": "Metronidazole 400 mg",
    "Norflox 400": "Norfloxacin 400 mg",
}
_LOWER = {n.lower(): n for n in VERIFIED}


def check_medicine(name: str) -> dict:
    """{status: verified|suggest|unrecognized|unclear, suggestion: str|None, generic: str}"""
    n = " ".join(str(name).lower().split())
    if not n or "unclear" in n:
        return {"status": "unclear", "suggestion": None}
    if n in _LOWER:
        return {"status": "verified", "suggestion": None, "generic": VERIFIED[_LOWER[n]]}
    close = difflib.get_close_matches(n, _LOWER, n=1, cutoff=0.8)
    if close:
        return {"status": "suggest", "suggestion": _LOWER[close[0]]}
    return {"status": "unrecognized", "suggestion": None}


def explain_frequency(freq: str) -> str:
    """'1-0-1 after food, 30 days' -> 'Morning and night, after food, for 30 days'."""
    freq = str(freq)
    if "UNCLEAR" in freq.upper():
        return "Not readable on the slip. Ask your doctor or pharmacist before taking this."
    m = re.match(r"\s*(\d)\s*-\s*(\d)\s*-\s*(\d)\s*(.*)", freq)
    if not m:
        return freq
    slots = [s for s, c in zip(("morning", "afternoon", "night"), m.groups()[:3]) if c != "0"]
    when = ", ".join(slots[:-1]) + " and " + slots[-1] if len(slots) > 1 else (slots or ["as directed"])[0]
    rest = re.sub(r"\b(at )?(morning|afternoon|night)\b", "", m[4], flags=re.I)  # already said by the slots
    rest = re.sub(r",?\s*\b(?:x\s*)?(\d+)\s*days?\b", r", for \1 days", rest)  # "x 3 days" / ", 3 days"
    rest = re.sub(r"\s*,\s*(,\s*)*", ", ", rest).strip(" ,")
    return f"{when.capitalize()}, {rest}" if rest else when.capitalize()


if __name__ == "__main__":  # self-check: python backend/safety.py
    assert explain_frequency("1-0-1 after food, 30 days") == "Morning and night, after food, for 30 days"
    assert explain_frequency("1-0-0 morning, 30 days") == "Morning, for 30 days"
    assert explain_frequency("UNCLEAR").startswith("Not readable")
    assert explain_frequency("BD") == "BD"
    assert explain_frequency("1 - 1 - 1 after food x 3 days") == "Morning, afternoon and night, after food, for 3 days"
    assert check_medicine("Folite") == {"status": "suggest", "suggestion": "Folvite"}
    assert check_medicine("dolo  650")["generic"] == "Paracetamol 650 mg"
    assert check_medicine("Zentrovix")["status"] == "unrecognized"
    assert check_medicine("Lumorin")["status"] == "unrecognized"
    assert check_medicine("UNCLEAR")["status"] == check_medicine("")["status"] == "unclear"
    print("ok")
